export {default as Header} from './header/Header'
export {default as About} from './about/About'
export {default as Projects} from './projects/Projects'
export {default as Contacts} from './contacts/Contacts'
export {default as Footer} from './footer/Footer'